sudo: false
install: make ninja
language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

script:
  - cd ousiac && cmake . -G "Unix Makefiles" && make && make test
