# Please keep the list alphabetically sorted!
# Fields:
#   * name
#   * username (GitHub)
#   * email
#   * address
#   * PGP
#   * description
#   * website

[[authors]]
name = "Filippo Costa"
username = "neysofu"
address = ["Via Giustiniano, 9", "Trieste 34133 (TS)", "ITALY"]
email = "filippocosta.italy@gmail.com"
description = "Lead developer"
website = "https://twitter.com/neysofu"
