# Please keep the list alphabetically sorted!
# Fields:
#   * name (name surname)
#   * username (GitHub)
#   * email
#   * address
#   * PGP
#   * description
#   * website

[[authors]]
name = "Filippo Costa"
username = "neysofu"
email = "filippocosta.italy@gmail.com"
description = "Lead developer"
website = "https://twitter.com/neysofu"

[[authors]]
name = "William Swinton"
description = "Logo (drawing of Plato)"

[[projects]]
name = "Category Theory for Programmers"
by = "Bartosz Milewski"
website = "https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface"
license = "CC BY-SA 4.0"
