[package]
name = "oa"
version = "0.1.0"
build = "build.rs"

[dependencies]
clap = {version = "2.31.2", features = []}
colored = "1.6.0"
exitcode = "1.1.2"
fst = "0.3.0"
fst-levenshtein = "0.2.0"
humantime = "1.1.1"
indexmap = "1.0.0"
serde_json = "1.0.11"

[build-dependencies]
humantime = "1.1.1"
